### ISSUE TITLE
Could you take over or replace AUR's bunsen-themes-git?

### ISSUE THREAD

**Issue by 2ion** [ARCHLabs/Archlabs-Icon-Themes#1]
See https://aur.archlinux.org/packages/bunsen-themes-git.

I do not currently have the capacity to maintain the Arch ports of BL stuff. I thought of requesting the package to be deleted.

Would you be interested in publishing this theme package as an alternative? The GTK3 stuff in the BL package is not working with Arch anymore anyway, and it is going to take some time until we have something gtk3.20+ officially.

**Comment by Dobbie03** [comment]
Hi,

I can take this over.  I have little to no experience in this area, so it is a learn as I go process.

Cheers

**Comment by erikdubois** [comment]
closing this one for new release 3.4.1
